### ISSUE TITLE
Fatal error in genesis_oik_a2z_query_letter_taxonomy() 

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/genesis-oik#19]
When visiting URL `https://s.b/oikcom/category/events/custom-css-events/` I get the following Fatal error with PHP 8.3

Fatal error: Uncaught TypeError: Cannot access offset of type array in isset or empty in C:\apache\htdocs\wordpress\wp-content\plugins\oik-bwtrace\libs\oik_boot.php:133 

```
Stack trace: 
#0 C:\apache\htdocs\wordpress\wp-content\themes\genesis-oik\functions.php(322): bw_array_get(Array, Array, 'letters') 
#1 C:\apache\htdocs\wordpress\wp-content\themes\genesis-oik\functions.php(289): genesis_oik_a2z_query_letter_taxonomy('letters', Array) 
#2 C:\apache\htdocs\oikcom\wp-includes\class-wp-hook.php(324): genesis_oik_a2z('') 
#3 C:\apache\htdocs\oikcom\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters('', Array) 
#4 C:\apache\htdocs\oikcom\wp-includes\plugin.php(517): WP_Hook->do_action(Array) 
#5 C:\apache\htdocs\wordpress\wp-content\themes\genesis\lib\framework.php(59): do_action('genesis_before_...') 
#6 C:\apache\htdocs\wordpress\wp-content\themes\genesis-oik\category.php(85): genesis() 
#7 C:\apache\htdocs\oikcom\wp-includes\template-loader.php(106): include('C:\\apache\\htdoc...') 
#8 C:\apache\htdocs\oikcom\wp-blog-header.php(19): require_once('C:\\apache\\htdoc...') 
#9 C:\apache\htdocs\oikcom\index.php(17): require('C:\\apache\\htdoc...') 
#10 {main} thrown in C:\apache\htdocs\wordpress\wp-content\plugins\oik-bwtrace\libs\oik_boot.php on line 133
```

On `https://www.oik-plugins.com/category/events/custom-css-events/` I get two Warnings. 

Warning: Illegal offset type in isset or empty in /home/customer/www/oik-plugins.com/public_html/wp-content/plugins/oik-bwtrace/libs/oik_boot.php on line 133

Warning: array_key_exists(): The first argument should be either a string or an integer in /home/customer/www/oik-plugins.com/public_html/wp-content/plugins/oik-bwtrace/libs/oik_boot.php on line 133

**Comment by bobbingwide** [comment]
Delivered in v1.3.3 to oik-plugins.co.uk and oik-plugins.com
